(let ([$5 (let ([$0 1]) (let ([$1 2]) (let ([$2 3]) (let ([$3 4])
                    (let ([_ (if (< (+ (global-value free_ptr) bytes)
                                    (global-value fromspace_end))
                                 (void)
                                 (collectbytes))])
                      (let ([$4 (allocate 32 (int int int int))])
                        (let ([_ (vector-set! $4 0 $0)])
                          (let ([_ (vector-set! $4 1 $1)])
                            (let ([_ (vector-set! $4 2 $2)])
                              (let ([_ (vector-set! $4 3 $3)])
                                $4))))))))))])
  (let ([$6 2])
    (let ([$7 3])
      (let ([$8 4])
        (let ([$9 (if (< (+ (global-value free_ptr) bytes)
                        (global-value fromspace_end))
                     (void)
                     (collectbytes))])
          (let ([_ (allocate 32 ((int int int int) int int int))])
            (let ([_ (vector-set! $9 0 $0)])
              (let ([_ (vector-set! $9 1 $1)])
                (let ([_ (vector-set! $9 2 $2)])
                  (let ([_ (vector-set! $9 3 $3)])
                    $9))))))))))